#
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "https://docs.pixiray.ninja"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-feed

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Pixiray the Ninja docs
# Website language
lang: en-US
# Header Title
header-title: <strong>Pixiray Ninjas</strong>
# Header Tagline
headter-tagline: Welcome to

####################################
######  Global Social Links   ######
####################################
youtube: "#"
pinterest: "#"
facebook: "#"
twitter: "https://twitter.com/pixiray"
google-plus: "#"
vimeo: "#"

#####################################
#############   Footer   ############
#####################################
footer-description: 
footer-copyright-text: Pixiray.ninja, GbR.
footer-copyright-url: https://pixiray.ninja
footer-copyright-year: 2023